// Mocks generated by Mockito 5.4.6 from annotations
// in piction_ai_ry/test/unit/services/challenge_state_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:piction_ai_ry/interfaces/facades/challenge_facade_interface.dart'
    as _i3;
import 'package:piction_ai_ry/models/challenge.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChallenge_0 extends _i1.SmartFake implements _i2.Challenge {
  _FakeChallenge_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IChallengeFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockIChallengeFacade extends _i1.Mock implements _i3.IChallengeFacade {
  MockIChallengeFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Challenge> get myChallenges =>
      (super.noSuchMethod(
            Invocation.getter(#myChallenges),
            returnValue: <_i2.Challenge>[],
          )
          as List<_i2.Challenge>);

  @override
  List<_i2.Challenge> get challengesToGuess =>
      (super.noSuchMethod(
            Invocation.getter(#challengesToGuess),
            returnValue: <_i2.Challenge>[],
          )
          as List<_i2.Challenge>);

  @override
  _i4.Stream<List<_i2.Challenge>> get challengesStream =>
      (super.noSuchMethod(
            Invocation.getter(#challengesStream),
            returnValue: _i4.Stream<List<_i2.Challenge>>.empty(),
          )
          as _i4.Stream<List<_i2.Challenge>>);

  @override
  _i4.Future<_i2.Challenge> sendChallenge(
    String? gameSessionId,
    String? article1,
    String? input1,
    String? preposition,
    String? article2,
    String? input2,
    List<String>? forbiddenWords,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendChallenge, [
              gameSessionId,
              article1,
              input1,
              preposition,
              article2,
              input2,
              forbiddenWords,
            ]),
            returnValue: _i4.Future<_i2.Challenge>.value(
              _FakeChallenge_0(
                this,
                Invocation.method(#sendChallenge, [
                  gameSessionId,
                  article1,
                  input1,
                  preposition,
                  article2,
                  input2,
                  forbiddenWords,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Challenge>);

  @override
  _i4.Future<List<_i2.Challenge>> getMyChallenges(String? gameSessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getMyChallenges, [gameSessionId]),
            returnValue: _i4.Future<List<_i2.Challenge>>.value(
              <_i2.Challenge>[],
            ),
          )
          as _i4.Future<List<_i2.Challenge>>);

  @override
  _i4.Future<List<_i2.Challenge>> getMyChallengesToGuess(
    String? gameSessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMyChallengesToGuess, [gameSessionId]),
            returnValue: _i4.Future<List<_i2.Challenge>>.value(
              <_i2.Challenge>[],
            ),
          )
          as _i4.Future<List<_i2.Challenge>>);

  @override
  _i4.Future<void> refreshMyChallenges() =>
      (super.noSuchMethod(
            Invocation.method(#refreshMyChallenges, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> refreshChallengesToGuess() =>
      (super.noSuchMethod(
            Invocation.method(#refreshChallengesToGuess, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> generateImageForChallenge(
    String? gameSessionId,
    String? challengeId,
    String? prompt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateImageForChallenge, [
              gameSessionId,
              challengeId,
              prompt,
            ]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#generateImageForChallenge, [
                  gameSessionId,
                  challengeId,
                  prompt,
                ]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> answerChallenge(
    String? gameSessionId,
    String? challengeId,
    String? answer,
    bool? isResolved,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#answerChallenge, [
              gameSessionId,
              challengeId,
              answer,
              isResolved,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Challenge>> listSessionChallenges(
    String? gameSessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listSessionChallenges, [gameSessionId]),
            returnValue: _i4.Future<List<_i2.Challenge>>.value(
              <_i2.Challenge>[],
            ),
          )
          as _i4.Future<List<_i2.Challenge>>);
}
