// Mocks generated by Mockito 5.4.6 from annotations
// in piction_ai_ry/test/unit/services/challenge_state_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;
import 'package:piction_ai_ry/managers/auth_manager.dart' as _i2;
import 'package:piction_ai_ry/managers/challenge_manager.dart' as _i5;
import 'package:piction_ai_ry/managers/game_state_manager.dart' as _i7;
import 'package:piction_ai_ry/managers/role_manager.dart' as _i6;
import 'package:piction_ai_ry/managers/score_manager.dart' as _i8;
import 'package:piction_ai_ry/managers/session_manager.dart' as _i3;
import 'package:piction_ai_ry/managers/team_manager.dart' as _i4;
import 'package:piction_ai_ry/managers/timer_manager.dart' as _i9;
import 'package:piction_ai_ry/models/challenge.dart' as _i12;
import 'package:piction_ai_ry/models/game_session.dart' as _i11;
import 'package:piction_ai_ry/models/player.dart' as _i10;
import 'package:piction_ai_ry/services/game_facade.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthManager_0 extends _i1.SmartFake implements _i2.AuthManager {
  _FakeAuthManager_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSessionManager_1 extends _i1.SmartFake
    implements _i3.SessionManager {
  _FakeSessionManager_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTeamManager_2 extends _i1.SmartFake implements _i4.TeamManager {
  _FakeTeamManager_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChallengeManager_3 extends _i1.SmartFake
    implements _i5.ChallengeManager {
  _FakeChallengeManager_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRoleManager_4 extends _i1.SmartFake implements _i6.RoleManager {
  _FakeRoleManager_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGameStateManager_5 extends _i1.SmartFake
    implements _i7.GameStateManager {
  _FakeGameStateManager_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeScoreManager_6 extends _i1.SmartFake implements _i8.ScoreManager {
  _FakeScoreManager_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTimerManager_7 extends _i1.SmartFake implements _i9.TimerManager {
  _FakeTimerManager_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlayer_8 extends _i1.SmartFake implements _i10.Player {
  _FakePlayer_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGameSession_9 extends _i1.SmartFake implements _i11.GameSession {
  _FakeGameSession_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChallenge_10 extends _i1.SmartFake implements _i12.Challenge {
  _FakeChallenge_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GameFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameFacade extends _i1.Mock implements _i13.GameFacade {
  MockGameFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthManager get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuthManager_0(this, Invocation.getter(#auth)),
          )
          as _i2.AuthManager);

  @override
  _i3.SessionManager get session =>
      (super.noSuchMethod(
            Invocation.getter(#session),
            returnValue: _FakeSessionManager_1(
              this,
              Invocation.getter(#session),
            ),
          )
          as _i3.SessionManager);

  @override
  _i4.TeamManager get team =>
      (super.noSuchMethod(
            Invocation.getter(#team),
            returnValue: _FakeTeamManager_2(this, Invocation.getter(#team)),
          )
          as _i4.TeamManager);

  @override
  _i5.ChallengeManager get challenge =>
      (super.noSuchMethod(
            Invocation.getter(#challenge),
            returnValue: _FakeChallengeManager_3(
              this,
              Invocation.getter(#challenge),
            ),
          )
          as _i5.ChallengeManager);

  @override
  _i6.RoleManager get role =>
      (super.noSuchMethod(
            Invocation.getter(#role),
            returnValue: _FakeRoleManager_4(this, Invocation.getter(#role)),
          )
          as _i6.RoleManager);

  @override
  _i7.GameStateManager get gameState =>
      (super.noSuchMethod(
            Invocation.getter(#gameState),
            returnValue: _FakeGameStateManager_5(
              this,
              Invocation.getter(#gameState),
            ),
          )
          as _i7.GameStateManager);

  @override
  _i8.ScoreManager get score =>
      (super.noSuchMethod(
            Invocation.getter(#score),
            returnValue: _FakeScoreManager_6(this, Invocation.getter(#score)),
          )
          as _i8.ScoreManager);

  @override
  _i9.TimerManager get timer =>
      (super.noSuchMethod(
            Invocation.getter(#timer),
            returnValue: _FakeTimerManager_7(this, Invocation.getter(#timer)),
          )
          as _i9.TimerManager);

  @override
  List<_i12.Challenge> get myChallenges =>
      (super.noSuchMethod(
            Invocation.getter(#myChallenges),
            returnValue: <_i12.Challenge>[],
          )
          as List<_i12.Challenge>);

  @override
  List<_i12.Challenge> get challengesToGuess =>
      (super.noSuchMethod(
            Invocation.getter(#challengesToGuess),
            returnValue: <_i12.Challenge>[],
          )
          as List<_i12.Challenge>);

  @override
  _i14.Stream<_i10.Player?> get playerStream =>
      (super.noSuchMethod(
            Invocation.getter(#playerStream),
            returnValue: _i14.Stream<_i10.Player?>.empty(),
          )
          as _i14.Stream<_i10.Player?>);

  @override
  _i14.Stream<_i11.GameSession?> get gameSessionStream =>
      (super.noSuchMethod(
            Invocation.getter(#gameSessionStream),
            returnValue: _i14.Stream<_i11.GameSession?>.empty(),
          )
          as _i14.Stream<_i11.GameSession?>);

  @override
  _i14.Stream<String> get statusStream =>
      (super.noSuchMethod(
            Invocation.getter(#statusStream),
            returnValue: _i14.Stream<String>.empty(),
          )
          as _i14.Stream<String>);

  @override
  _i14.Stream<String?> get phaseStream =>
      (super.noSuchMethod(
            Invocation.getter(#phaseStream),
            returnValue: _i14.Stream<String?>.empty(),
          )
          as _i14.Stream<String?>);

  @override
  _i14.Stream<List<_i12.Challenge>> get challengesStream =>
      (super.noSuchMethod(
            Invocation.getter(#challengesStream),
            returnValue: _i14.Stream<List<_i12.Challenge>>.empty(),
          )
          as _i14.Stream<List<_i12.Challenge>>);

  @override
  String get currentStatus =>
      (super.noSuchMethod(
            Invocation.getter(#currentStatus),
            returnValue: _i15.dummyValue<String>(
              this,
              Invocation.getter(#currentStatus),
            ),
          )
          as String);

  @override
  bool get isGameActive =>
      (super.noSuchMethod(Invocation.getter(#isGameActive), returnValue: false)
          as bool);

  @override
  bool get isGameFinished =>
      (super.noSuchMethod(
            Invocation.getter(#isGameFinished),
            returnValue: false,
          )
          as bool);

  @override
  int get redTeamScore =>
      (super.noSuchMethod(Invocation.getter(#redTeamScore), returnValue: 0)
          as int);

  @override
  int get blueTeamScore =>
      (super.noSuchMethod(Invocation.getter(#blueTeamScore), returnValue: 0)
          as int);

  @override
  _i14.Stream<Map<String, int>> get scoreStream =>
      (super.noSuchMethod(
            Invocation.getter(#scoreStream),
            returnValue: _i14.Stream<Map<String, int>>.empty(),
          )
          as _i14.Stream<Map<String, int>>);

  @override
  int get remainingSeconds =>
      (super.noSuchMethod(Invocation.getter(#remainingSeconds), returnValue: 0)
          as int);

  @override
  _i14.Stream<int> get timerStream =>
      (super.noSuchMethod(
            Invocation.getter(#timerStream),
            returnValue: _i14.Stream<int>.empty(),
          )
          as _i14.Stream<int>);

  @override
  set auth(_i2.AuthManager? _auth) => super.noSuchMethod(
    Invocation.setter(#auth, _auth),
    returnValueForMissingStub: null,
  );

  @override
  set session(_i3.SessionManager? _session) => super.noSuchMethod(
    Invocation.setter(#session, _session),
    returnValueForMissingStub: null,
  );

  @override
  set team(_i4.TeamManager? _team) => super.noSuchMethod(
    Invocation.setter(#team, _team),
    returnValueForMissingStub: null,
  );

  @override
  set challenge(_i5.ChallengeManager? _challenge) => super.noSuchMethod(
    Invocation.setter(#challenge, _challenge),
    returnValueForMissingStub: null,
  );

  @override
  set role(_i6.RoleManager? _role) => super.noSuchMethod(
    Invocation.setter(#role, _role),
    returnValueForMissingStub: null,
  );

  @override
  set gameState(_i7.GameStateManager? _gameState) => super.noSuchMethod(
    Invocation.setter(#gameState, _gameState),
    returnValueForMissingStub: null,
  );

  @override
  set score(_i8.ScoreManager? _score) => super.noSuchMethod(
    Invocation.setter(#score, _score),
    returnValueForMissingStub: null,
  );

  @override
  set timer(_i9.TimerManager? _timer) => super.noSuchMethod(
    Invocation.setter(#timer, _timer),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<_i10.Player> loginWithUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithUsername, [username]),
            returnValue: _i14.Future<_i10.Player>.value(
              _FakePlayer_8(
                this,
                Invocation.method(#loginWithUsername, [username]),
              ),
            ),
          )
          as _i14.Future<_i10.Player>);

  @override
  _i14.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<_i11.GameSession> createGameSession() =>
      (super.noSuchMethod(
            Invocation.method(#createGameSession, []),
            returnValue: _i14.Future<_i11.GameSession>.value(
              _FakeGameSession_9(
                this,
                Invocation.method(#createGameSession, []),
              ),
            ),
          )
          as _i14.Future<_i11.GameSession>);

  @override
  _i14.Future<void> joinGameSession(String? gameSessionId, String? color) =>
      (super.noSuchMethod(
            Invocation.method(#joinGameSession, [gameSessionId, color]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> joinAvailableTeam(String? gameSessionId) =>
      (super.noSuchMethod(
            Invocation.method(#joinAvailableTeam, [gameSessionId]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> refreshGameSession(String? gameSessionId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshGameSession, [gameSessionId]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> leaveGameSession() =>
      (super.noSuchMethod(
            Invocation.method(#leaveGameSession, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> startGameSession() =>
      (super.noSuchMethod(
            Invocation.method(#startGameSession, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> changeTeam(String? gameSessionId, String? newTeamColor) =>
      (super.noSuchMethod(
            Invocation.method(#changeTeam, [gameSessionId, newTeamColor]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<_i12.Challenge> sendChallenge(
    String? gameSessionId,
    String? article1,
    String? input1,
    String? preposition,
    String? article2,
    String? input2,
    List<String>? forbiddenWords,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendChallenge, [
              gameSessionId,
              article1,
              input1,
              preposition,
              article2,
              input2,
              forbiddenWords,
            ]),
            returnValue: _i14.Future<_i12.Challenge>.value(
              _FakeChallenge_10(
                this,
                Invocation.method(#sendChallenge, [
                  gameSessionId,
                  article1,
                  input1,
                  preposition,
                  article2,
                  input2,
                  forbiddenWords,
                ]),
              ),
            ),
          )
          as _i14.Future<_i12.Challenge>);

  @override
  _i14.Future<List<_i12.Challenge>> getMyChallenges(String? gameSessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getMyChallenges, [gameSessionId]),
            returnValue: _i14.Future<List<_i12.Challenge>>.value(
              <_i12.Challenge>[],
            ),
          )
          as _i14.Future<List<_i12.Challenge>>);

  @override
  _i14.Future<List<_i12.Challenge>> getMyChallengesToGuess(
    String? gameSessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMyChallengesToGuess, [gameSessionId]),
            returnValue: _i14.Future<List<_i12.Challenge>>.value(
              <_i12.Challenge>[],
            ),
          )
          as _i14.Future<List<_i12.Challenge>>);

  @override
  _i14.Future<void> refreshMyChallenges() =>
      (super.noSuchMethod(
            Invocation.method(#refreshMyChallenges, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> refreshChallengesToGuess() =>
      (super.noSuchMethod(
            Invocation.method(#refreshChallengesToGuess, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<String> generateImageForChallenge(
    String? gameSessionId,
    String? challengeId,
    String? prompt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateImageForChallenge, [
              gameSessionId,
              challengeId,
              prompt,
            ]),
            returnValue: _i14.Future<String>.value(
              _i15.dummyValue<String>(
                this,
                Invocation.method(#generateImageForChallenge, [
                  gameSessionId,
                  challengeId,
                  prompt,
                ]),
              ),
            ),
          )
          as _i14.Future<String>);

  @override
  _i14.Future<void> answerChallenge(
    String? gameSessionId,
    String? challengeId,
    String? answer,
    bool? isResolved,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#answerChallenge, [
              gameSessionId,
              challengeId,
              answer,
              isResolved,
            ]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<List<_i12.Challenge>> listSessionChallenges(
    String? gameSessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listSessionChallenges, [gameSessionId]),
            returnValue: _i14.Future<List<_i12.Challenge>>.value(
              <_i12.Challenge>[],
            ),
          )
          as _i14.Future<List<_i12.Challenge>>);

  @override
  void applyScoreDelta(String? teamColor, int? delta) => super.noSuchMethod(
    Invocation.method(#applyScoreDelta, [teamColor, delta]),
    returnValueForMissingStub: null,
  );

  @override
  void initializeScores() => super.noSuchMethod(
    Invocation.method(#initializeScores, []),
    returnValueForMissingStub: null,
  );

  @override
  void startTimer({required void Function()? onEnd}) => super.noSuchMethod(
    Invocation.method(#startTimer, [], {#onEnd: onEnd}),
    returnValueForMissingStub: null,
  );

  @override
  void stopTimer() => super.noSuchMethod(
    Invocation.method(#stopTimer, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
