// Mocks generated by Mockito 5.4.6 from annotations
// in piction_ai_ry/test/services/facades/auth_facade_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:piction_ai_ry/interfaces/auth_api_interface.dart' as _i3;
import 'package:piction_ai_ry/models/player.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlayer_0 extends _i1.SmartFake implements _i2.Player {
  _FakePlayer_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAuthApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthApi extends _i1.Mock implements _i3.IAuthApi {
  MockIAuthApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  _i4.Future<_i2.Player> createPlayer(String? name, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#createPlayer, [name, password]),
            returnValue: _i4.Future<_i2.Player>.value(
              _FakePlayer_0(
                this,
                Invocation.method(#createPlayer, [name, password]),
              ),
            ),
          )
          as _i4.Future<_i2.Player>);

  @override
  _i4.Future<String> login(String? name, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [name, password]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#login, [name, password]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> loginWithUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithUsername, [username]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#loginWithUsername, [username]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i2.Player> getMe() =>
      (super.noSuchMethod(
            Invocation.method(#getMe, []),
            returnValue: _i4.Future<_i2.Player>.value(
              _FakePlayer_0(this, Invocation.method(#getMe, [])),
            ),
          )
          as _i4.Future<_i2.Player>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
