// Mocks generated by Mockito 5.4.6 from annotations
// in piction_ai_ry/test/services/facades/session_facade_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:piction_ai_ry/interfaces/facades/auth_facade_interface.dart'
    as _i7;
import 'package:piction_ai_ry/interfaces/session_api_interface.dart' as _i4;
import 'package:piction_ai_ry/managers/role_manager.dart' as _i9;
import 'package:piction_ai_ry/managers/team_manager.dart' as _i8;
import 'package:piction_ai_ry/models/game_session.dart' as _i2;
import 'package:piction_ai_ry/models/player.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGameSession_0 extends _i1.SmartFake implements _i2.GameSession {
  _FakeGameSession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlayer_1 extends _i1.SmartFake implements _i3.Player {
  _FakePlayer_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ISessionApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockISessionApi extends _i1.Mock implements _i4.ISessionApi {
  MockISessionApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.GameSession> createGameSession() =>
      (super.noSuchMethod(
            Invocation.method(#createGameSession, []),
            returnValue: _i5.Future<_i2.GameSession>.value(
              _FakeGameSession_0(
                this,
                Invocation.method(#createGameSession, []),
              ),
            ),
          )
          as _i5.Future<_i2.GameSession>);

  @override
  _i5.Future<void> joinGameSession(String? gameSessionId, String? color) =>
      (super.noSuchMethod(
            Invocation.method(#joinGameSession, [gameSessionId, color]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> leaveGameSession(String? gameSessionId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveGameSession, [gameSessionId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.GameSession> getGameSession(String? gameSessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getGameSession, [gameSessionId]),
            returnValue: _i5.Future<_i2.GameSession>.value(
              _FakeGameSession_0(
                this,
                Invocation.method(#getGameSession, [gameSessionId]),
              ),
            ),
          )
          as _i5.Future<_i2.GameSession>);

  @override
  _i5.Future<String> getGameSessionStatus(String? gameSessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getGameSessionStatus, [gameSessionId]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getGameSessionStatus, [gameSessionId]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> startGameSession(String? gameSessionId) =>
      (super.noSuchMethod(
            Invocation.method(#startGameSession, [gameSessionId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [IAuthFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthFacade extends _i1.Mock implements _i7.IAuthFacade {
  MockIAuthFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i3.Player?> get playerStream =>
      (super.noSuchMethod(
            Invocation.getter(#playerStream),
            returnValue: _i5.Stream<_i3.Player?>.empty(),
          )
          as _i5.Stream<_i3.Player?>);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  _i5.Future<_i3.Player> loginWithUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithUsername, [username]),
            returnValue: _i5.Future<_i3.Player>.value(
              _FakePlayer_1(
                this,
                Invocation.method(#loginWithUsername, [username]),
              ),
            ),
          )
          as _i5.Future<_i3.Player>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [TeamManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeamManager extends _i1.Mock implements _i8.TeamManager {
  MockTeamManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> getAvailableTeamColor(String? gameSessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableTeamColor, [gameSessionId]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getAvailableTeamColor, [gameSessionId]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> changeTeam(String? gameSessionId, String? newColor) =>
      (super.noSuchMethod(
            Invocation.method(#changeTeam, [gameSessionId, newColor]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> joinAvailableTeam(
    String? gameSessionId,
    String? currentPlayerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#joinAvailableTeam, [
              gameSessionId,
              currentPlayerId,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> safeJoinGameSession(String? gameSessionId, String? color) =>
      (super.noSuchMethod(
            Invocation.method(#safeJoinGameSession, [gameSessionId, color]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  Map<String, int> getTeamStats(_i2.GameSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#getTeamStats, [session]),
            returnValue: <String, int>{},
          )
          as Map<String, int>);
}

/// A class which mocks [RoleManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoleManager extends _i1.Mock implements _i9.RoleManager {
  MockRoleManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String? getPlayerRole(String? playerId, _i2.GameSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#getPlayerRole, [playerId, session]),
          )
          as String?);

  @override
  bool isPlayerDrawer(String? playerId, _i2.GameSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#isPlayerDrawer, [playerId, session]),
            returnValue: false,
          )
          as bool);

  @override
  bool isPlayerGuesser(String? playerId, _i2.GameSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#isPlayerGuesser, [playerId, session]),
            returnValue: false,
          )
          as bool);

  @override
  _i2.GameSession assignInitialRoles(_i2.GameSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#assignInitialRoles, [session]),
            returnValue: _FakeGameSession_0(
              this,
              Invocation.method(#assignInitialRoles, [session]),
            ),
          )
          as _i2.GameSession);

  @override
  bool allPlayersHaveRoles(_i2.GameSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#allPlayersHaveRoles, [session]),
            returnValue: false,
          )
          as bool);

  @override
  bool areRolesValid(_i2.GameSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#areRolesValid, [session]),
            returnValue: false,
          )
          as bool);
}
