// Mocks generated by Mockito 5.4.6 from annotations
// in piction_ai_ry/test/viewmodels/game_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:piction_ai_ry/interfaces/facades/challenge_facade_interface.dart'
    as _i6;
import 'package:piction_ai_ry/interfaces/facades/game_state_facade_interface.dart'
    as _i8;
import 'package:piction_ai_ry/interfaces/facades/score_facade_interface.dart'
    as _i9;
import 'package:piction_ai_ry/interfaces/facades/session_facade_interface.dart'
    as _i4;
import 'package:piction_ai_ry/models/challenge.dart' as _i3;
import 'package:piction_ai_ry/models/game_session.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGameSession_0 extends _i1.SmartFake implements _i2.GameSession {
  _FakeGameSession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChallenge_1 extends _i1.SmartFake implements _i3.Challenge {
  _FakeChallenge_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ISessionFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockISessionFacade extends _i1.Mock implements _i4.ISessionFacade {
  MockISessionFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i2.GameSession?> get gameSessionStream =>
      (super.noSuchMethod(
            Invocation.getter(#gameSessionStream),
            returnValue: _i5.Stream<_i2.GameSession?>.empty(),
          )
          as _i5.Stream<_i2.GameSession?>);

  @override
  _i5.Future<_i2.GameSession> createGameSession() =>
      (super.noSuchMethod(
            Invocation.method(#createGameSession, []),
            returnValue: _i5.Future<_i2.GameSession>.value(
              _FakeGameSession_0(
                this,
                Invocation.method(#createGameSession, []),
              ),
            ),
          )
          as _i5.Future<_i2.GameSession>);

  @override
  _i5.Future<void> joinGameSession(String? gameSessionId, String? color) =>
      (super.noSuchMethod(
            Invocation.method(#joinGameSession, [gameSessionId, color]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> joinAvailableTeam(String? gameSessionId) =>
      (super.noSuchMethod(
            Invocation.method(#joinAvailableTeam, [gameSessionId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> refreshGameSession(String? gameSessionId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshGameSession, [gameSessionId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> leaveGameSession() =>
      (super.noSuchMethod(
            Invocation.method(#leaveGameSession, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> startGameSession() =>
      (super.noSuchMethod(
            Invocation.method(#startGameSession, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> changeTeam(String? gameSessionId, String? newTeamColor) =>
      (super.noSuchMethod(
            Invocation.method(#changeTeam, [gameSessionId, newTeamColor]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [IChallengeFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockIChallengeFacade extends _i1.Mock implements _i6.IChallengeFacade {
  MockIChallengeFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Challenge> get myChallenges =>
      (super.noSuchMethod(
            Invocation.getter(#myChallenges),
            returnValue: <_i3.Challenge>[],
          )
          as List<_i3.Challenge>);

  @override
  List<_i3.Challenge> get challengesToGuess =>
      (super.noSuchMethod(
            Invocation.getter(#challengesToGuess),
            returnValue: <_i3.Challenge>[],
          )
          as List<_i3.Challenge>);

  @override
  _i5.Stream<List<_i3.Challenge>> get challengesStream =>
      (super.noSuchMethod(
            Invocation.getter(#challengesStream),
            returnValue: _i5.Stream<List<_i3.Challenge>>.empty(),
          )
          as _i5.Stream<List<_i3.Challenge>>);

  @override
  _i5.Future<_i3.Challenge> sendChallenge(
    String? gameSessionId,
    String? article1,
    String? input1,
    String? preposition,
    String? article2,
    String? input2,
    List<String>? forbiddenWords,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendChallenge, [
              gameSessionId,
              article1,
              input1,
              preposition,
              article2,
              input2,
              forbiddenWords,
            ]),
            returnValue: _i5.Future<_i3.Challenge>.value(
              _FakeChallenge_1(
                this,
                Invocation.method(#sendChallenge, [
                  gameSessionId,
                  article1,
                  input1,
                  preposition,
                  article2,
                  input2,
                  forbiddenWords,
                ]),
              ),
            ),
          )
          as _i5.Future<_i3.Challenge>);

  @override
  _i5.Future<List<_i3.Challenge>> getMyChallenges(String? gameSessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getMyChallenges, [gameSessionId]),
            returnValue: _i5.Future<List<_i3.Challenge>>.value(
              <_i3.Challenge>[],
            ),
          )
          as _i5.Future<List<_i3.Challenge>>);

  @override
  _i5.Future<List<_i3.Challenge>> getMyChallengesToGuess(
    String? gameSessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMyChallengesToGuess, [gameSessionId]),
            returnValue: _i5.Future<List<_i3.Challenge>>.value(
              <_i3.Challenge>[],
            ),
          )
          as _i5.Future<List<_i3.Challenge>>);

  @override
  _i5.Future<void> refreshMyChallenges() =>
      (super.noSuchMethod(
            Invocation.method(#refreshMyChallenges, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> refreshChallengesToGuess() =>
      (super.noSuchMethod(
            Invocation.method(#refreshChallengesToGuess, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> generateImageForChallenge(
    String? gameSessionId,
    String? challengeId,
    String? prompt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateImageForChallenge, [
              gameSessionId,
              challengeId,
              prompt,
            ]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#generateImageForChallenge, [
                  gameSessionId,
                  challengeId,
                  prompt,
                ]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> answerChallenge(
    String? gameSessionId,
    String? challengeId,
    String? answer,
    bool? isResolved,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#answerChallenge, [
              gameSessionId,
              challengeId,
              answer,
              isResolved,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Challenge>> listSessionChallenges(
    String? gameSessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listSessionChallenges, [gameSessionId]),
            returnValue: _i5.Future<List<_i3.Challenge>>.value(
              <_i3.Challenge>[],
            ),
          )
          as _i5.Future<List<_i3.Challenge>>);
}

/// A class which mocks [IGameStateFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGameStateFacade extends _i1.Mock implements _i8.IGameStateFacade {
  MockIGameStateFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get currentStatus =>
      (super.noSuchMethod(
            Invocation.getter(#currentStatus),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#currentStatus),
            ),
          )
          as String);

  @override
  bool get isGameActive =>
      (super.noSuchMethod(Invocation.getter(#isGameActive), returnValue: false)
          as bool);

  @override
  bool get isGameFinished =>
      (super.noSuchMethod(
            Invocation.getter(#isGameFinished),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Stream<String> get statusStream =>
      (super.noSuchMethod(
            Invocation.getter(#statusStream),
            returnValue: _i5.Stream<String>.empty(),
          )
          as _i5.Stream<String>);

  @override
  _i5.Stream<String?> get phaseStream =>
      (super.noSuchMethod(
            Invocation.getter(#phaseStream),
            returnValue: _i5.Stream<String?>.empty(),
          )
          as _i5.Stream<String?>);

  @override
  void startGame() => super.noSuchMethod(
    Invocation.method(#startGame, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetToLobby() => super.noSuchMethod(
    Invocation.method(#resetToLobby, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> syncWithSession() =>
      (super.noSuchMethod(
            Invocation.method(#syncWithSession, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void startAutoSync() => super.noSuchMethod(
    Invocation.method(#startAutoSync, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopAutoSync() => super.noSuchMethod(
    Invocation.method(#stopAutoSync, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [IScoreFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockIScoreFacade extends _i1.Mock implements _i9.IScoreFacade {
  MockIScoreFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get redTeamScore =>
      (super.noSuchMethod(Invocation.getter(#redTeamScore), returnValue: 0)
          as int);

  @override
  int get blueTeamScore =>
      (super.noSuchMethod(Invocation.getter(#blueTeamScore), returnValue: 0)
          as int);

  @override
  _i5.Stream<Map<String, int>> get scoreStream =>
      (super.noSuchMethod(
            Invocation.getter(#scoreStream),
            returnValue: _i5.Stream<Map<String, int>>.empty(),
          )
          as _i5.Stream<Map<String, int>>);

  @override
  void applyScoreDelta(String? teamColor, int? delta) => super.noSuchMethod(
    Invocation.method(#applyScoreDelta, [teamColor, delta]),
    returnValueForMissingStub: null,
  );

  @override
  void setTeamScore(String? teamColor, int? score) => super.noSuchMethod(
    Invocation.method(#setTeamScore, [teamColor, score]),
    returnValueForMissingStub: null,
  );

  @override
  void initializeScores() => super.noSuchMethod(
    Invocation.method(#initializeScores, []),
    returnValueForMissingStub: null,
  );
}
