// Mocks generated by Mockito 5.4.6 from annotations
// in piction_ai_ry/test/viewmodels/lobby_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:piction_ai_ry/interfaces/facades/auth_facade_interface.dart'
    as _i4;
import 'package:piction_ai_ry/interfaces/facades/session_facade_interface.dart'
    as _i6;
import 'package:piction_ai_ry/models/game_session.dart' as _i3;
import 'package:piction_ai_ry/models/player.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlayer_0 extends _i1.SmartFake implements _i2.Player {
  _FakePlayer_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGameSession_1 extends _i1.SmartFake implements _i3.GameSession {
  _FakeGameSession_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAuthFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthFacade extends _i1.Mock implements _i4.IAuthFacade {
  MockIAuthFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i2.Player?> get playerStream =>
      (super.noSuchMethod(
            Invocation.getter(#playerStream),
            returnValue: _i5.Stream<_i2.Player?>.empty(),
          )
          as _i5.Stream<_i2.Player?>);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  _i5.Future<_i2.Player> loginWithUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithUsername, [username]),
            returnValue: _i5.Future<_i2.Player>.value(
              _FakePlayer_0(
                this,
                Invocation.method(#loginWithUsername, [username]),
              ),
            ),
          )
          as _i5.Future<_i2.Player>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ISessionFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockISessionFacade extends _i1.Mock implements _i6.ISessionFacade {
  MockISessionFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i3.GameSession?> get gameSessionStream =>
      (super.noSuchMethod(
            Invocation.getter(#gameSessionStream),
            returnValue: _i5.Stream<_i3.GameSession?>.empty(),
          )
          as _i5.Stream<_i3.GameSession?>);

  @override
  _i5.Future<_i3.GameSession> createGameSession() =>
      (super.noSuchMethod(
            Invocation.method(#createGameSession, []),
            returnValue: _i5.Future<_i3.GameSession>.value(
              _FakeGameSession_1(
                this,
                Invocation.method(#createGameSession, []),
              ),
            ),
          )
          as _i5.Future<_i3.GameSession>);

  @override
  _i5.Future<void> joinGameSession(String? gameSessionId, String? color) =>
      (super.noSuchMethod(
            Invocation.method(#joinGameSession, [gameSessionId, color]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> joinAvailableTeam(String? gameSessionId) =>
      (super.noSuchMethod(
            Invocation.method(#joinAvailableTeam, [gameSessionId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> refreshGameSession(String? gameSessionId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshGameSession, [gameSessionId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> leaveGameSession() =>
      (super.noSuchMethod(
            Invocation.method(#leaveGameSession, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> startGameSession() =>
      (super.noSuchMethod(
            Invocation.method(#startGameSession, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> changeTeam(String? gameSessionId, String? newTeamColor) =>
      (super.noSuchMethod(
            Invocation.method(#changeTeam, [gameSessionId, newTeamColor]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
